version: '3.7'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  postgres:
    driver: local
  redis:
    driver: local
  mysql:
    driver: local
  mariadb:
    driver: local
  netdata:
    driver: local
  portainer:
    driver: local


services:


  ### php-fpm ##############################################

  php-fpm:
    restart: always
    build:
      context: ./php-fpm
    volumes:
      # - ./php-fpm/config:/usr/local/etc
      - ${DIR_APP}:/var/www:${MOUNT}
      - ${DIR_LOG}/php:/var/log/php
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=serverName=asrorz
      - FAKETIME=-0
    networks:
      - backend
    depends_on:
      - mysql
      - postgres
    ports:
      - "220:22"
      - "29000:9000"
    stdin_open: true
    tty: true


  ### NGINX Server #########################################

  nginx:
    restart: always
    build:
      context: ./nginx
    volumes:
      - ${DIR_APP}:/var/www:${MOUNT}
      #- ${DIR_LOG}/nginx:/var/log/nginx
      #- ${DIR_LOG}/nginx-certify:/var/log/nginx-certify
      #- ${DIR_LOG}/nginx-redirec:/var/log/nginx-redirec
      #- ${DIR_LOG}/nginx-vhosts:/var/log/nginx-vhosts
      - ./nginx/config:/etc/nginx
      #- ./nginx/starts:/opt
    depends_on:
      - php-fpm
    ports:
      - "221:22"
      - "280:80"
      - "2443:443"
    networks:
      - frontend
      - backend
    stdin_open: true
    tty: true


  ### Mariadb Alpine
  ##############################################

  mariadb:
    restart: always
    build: ./mariadb
    volumes:
      - mariadb:/var/lib/mysql
      - ${DIR_LOG}/mariadb:/var/log/mysql
    ports:
      - "222:22"
      - "23306:3306"
    environment:
      - MYSQL_PWD=serverpass1234
      - MYSQL_ROOT_PASSWORD=serverpass1234
    networks:
      - backend
    stdin_open: true
    tty: true


  ###   Mariadb Alpine    ###   3
  ##############################################

  mysql:
    build: ./mysql
    restart: unless-stopped
    volumes:
      - mysql:/var/lib/mysql
      - ${DIR_LOG}/mysql:/var/log/mysql
    ports:
      - "223:22"
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=serverpass1234
    networks:
      - backend
    stdin_open: true
    tty: true



  ### PostgreSQL ###########################################

  postgres:
    restart: always
    build: ./postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    command: postgres -c config_file=/etc/postgres/postgresql.conf
    ports:
      - "224:22"
      - "25432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=serverpass1234
    networks:
      - backend
    stdin_open: true
    tty: true



  ### Redis ################################################
  redis:
    restart: always
    build: ./redis
    volumes:
      - redis:/data
    ports:
      - "226:22"
      - "26379:6379"
    networks:
      - backend
    stdin_open: true
    tty: true


  ### NetData ################################################
  
  netdata:
    build:
      context: ./netdata
    cap_add:
      - SYS_PTRACE
    volumes:
      - netdata:/host
    ports:
      - "228:22"
      - "39999:19999"
    networks:
      - backend
    stdin_open: true
    tty: true
    


  ### Portainer ################################################

  portainer:
    restart: always
    build:
      context: ./portainer
    volumes:
      - portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "229:22"
      - "39000:9000"
    networks:
      - backend
    stdin_open: true
    tty: true


